Doctors, appointments, schedules interactions
8Vinso8/HospitalWebsite pull request #3
Opened 2022-10-16 10:24 UTC by 8Vinso8

2022-10-16 10:57 UTC, Dezzelshipc approved these changes

2022-10-17 10:39 UTC, Vixorem requested changes

2022-10-17 10:39 UTC, Vixorem commented on domain/Service/DoctorService.cs
> +    var doctor = _db.GetDoctor(specialization);
А если таких докторов много

2022-10-17 10:39 UTC, Vixorem commented on domain/Service/AppointmentService.cs
> +    appointments.Sort((a, b) => a.StartTime < b.StartTime ? -1 : 1);
Посмотри про LINQ методы
Тут можно наверняка заиспользовать Any(x => *условие*) с параметром

2022-10-20 11:28 UTC, Vixorem requested changes

2022-10-20 11:28 UTC, Vixorem commented on domain/Logic/IAppointmentRepository.cs
> +  IEnumerable<Appointment> GetAppointments(int doctorId);
Эти методы для получения свободных дат. А тут возвращаются объекты, как будто они есть. По сути, свободные даты, это те, которые еще не существуют)
Тут надо возвращать что то типа
Список из дат
Ну, типа, с шагом по полчаса
Типа вот даты 8:00, 8:30 и ид, но чтоб свободные. Типа того

2022-10-21 08:03 UTC, Vixorem approved these changes

2022-10-21 08:07 UTC, merged